client:
	curl -H "Content-Type: application/json" -X POST -d "@sample-client.json" http://127.0.0.1:3000/api/v1/clients
ping:
	curl -H "Content-Type: application/json" -X GET http://127.0.0.1:3000/ping | jq
